### ISSUE TITLE
PR# 22 remove gulp-util

### ISSUE THREAD

**Issue by kyle-hensman** [SigwoTechnologies/jupiter-gravity#21]
**Why is this an issue**
Warnings of deprecated package in Jupiter-Gravity - gulp-util. We need to clean up these warnings in the Node Package Manager.

**What work needs to be done**
I found an article related to this procedure, will follow instructions to ensure gulp-util is replaced/removed correctly.
link:
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**What are the completion requirements**

- [x] Pull from Jupiter-Gravity (master branch)

- [x] Create issue-branch

- [x] Follow instructions in the link above

- [x] Ensure gulp-util was removed correctly

- [x] run tests to ensure this has not effected the functionality of the app.

- [x] Push issue-branch and create pull request for review.

**Comment by rafaeloaguir** [comment]
PR has been merged to master. Closing issue.
